Repository HSU-capston/Back, pull requests merged in 2025-03, with the labels that each got.

#2 [#1] Setting: 깃허브 템플릿 테스트, 스웨거 설정
  build.gradle
  src/main/java/capstone/SportyUp/SportyUp_Server/config/SwaggerConfig.java
  src/main/resources/cam/frame_1738567209.jpg
  src/main/resources/cam/frame_1738568983.jpg
Labels: ⚙️ setting

#5 Feat/#4
  .github/ISSUE_TEMPLATE/⚙️-setting.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/📝-docs.md
  .github/ISSUE_TEMPLATE/🔨-refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/capstone/SportyUp/SportyUp_Server/config/SwaggerConfig.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/TestController.java
Labels: ✨ feature

#6 Feat/#3
  build.gradle
  src/main/java/capstone/SportyUp/SportyUp_Server/apiPayload/ApiResponse.java
  src/main/java/capstone/SportyUp/SportyUp_Server/apiPayload/code/BaseCode.java
  src/main/java/capstone/SportyUp/SportyUp_Server/apiPayload/code/BaseErrorCode.java
  src/main/java/capstone/SportyUp/SportyUp_Server/apiPayload/code/ErrorReasonDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/apiPayload/code/ReasonDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/capstone/SportyUp/SportyUp_Server/apiPayload/code/status/SuccessStatus.java
  src/main/java/capstone/SportyUp/SportyUp_Server/config/SwaggerConfig.java
  src/main/java/capstone/SportyUp/SportyUp_Server/config/WebConfig.java
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/BowlingConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/BowlingService/BowlingCommandService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/BowlingService/BowlingCommandServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/BowlingDTO/BowlingRequestDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/BowlingDTO/BowlingResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/BowlingController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/TestController.java
Labels: ✨ feature

#12 [#11]Feat: Entity 작성
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/BowlingAnalyze.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/Game.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/Sports.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/User.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/UserSports.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/common/BaseEntity.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/enums/PoseScore.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/enums/UserSportsGoal.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/enums/UserStatus.java
Labels: ✨ feature

#13 [#10] Docs: API 명세서 작성
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/User.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/AnalyzeDTO/AnalyzeRequestDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/AnalyzeDTO/AnalyzeResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/GameDTO/GameRequestDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/GameDTO/GameResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/UserDTO/UserRequestDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/UserDTO/UserResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/AnalyzeController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/GameController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/UserController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/AnalyzeSpecification.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/GameSpecification.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/UserSpecification.java
Labels: 📝 docs

#15 [#14] Docs: API 명세서 수정, DTO 수정
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/AnalyzeDTO/AnalyzeResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/GameDTO/GameResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/SportsDTO/SportsRequestDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/SportsDTO/SportsResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/AnalyzeController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/GameController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/SportsController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/AnalyzeSpecification.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/GameSpecification.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/SportsSpecification.java
Labels: 📝 docs

#17 [#16]Feat: Game생성기능 구현
  src/main/java/capstone/SportyUp/SportyUp_Server/SportyUpServerApplication.java
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/GameConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/domain/Game.java
  src/main/java/capstone/SportyUp/SportyUp_Server/repository/GameRepository.java
  src/main/java/capstone/SportyUp/SportyUp_Server/repository/SportsRepository.java
  src/main/java/capstone/SportyUp/SportyUp_Server/repository/UserRepository.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameCommandService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameCommandServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/GameDTO/GameRequestDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/GameController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/GameSpecification.java
Labels: ✨ feature

#21 [#20]Feat: 게임 종료 API 구현
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/GameConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameCommandService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameCommandServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/GameDTO/GameResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/GameController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/GameSpecification.java
Labels: ✨ feature

#23 [#22]Feat: 스포츠 종목 조회 API 구현
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/SportsConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/SportsService/SportsQueryService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/SportsService/SportsQueryServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/SportsController.java
Labels: ✨ feature

#27 [#26]Setting: CI/CD 수정
  .github/workflows/dev_deploy.yml
Labels: ⚙️ setting

#28 [#26]Setting: CI/CD 한번더 수정
  .github/workflows/dev_deploy.yml
Labels: ⚙️ setting

#30 [#29] Feat: 차트탭 조회 API 구현
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/GameConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/repository/GameRepository.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/AnalyzeService/AnalyzeQueryService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/AnalyzeService/AnalyzeQueryServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameQueryService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameQueryServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/AnalyzeDTO/AnalyzeResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/GameDTO/GameResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/AnalyzeController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/GameController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/AnalyzeSpecification.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/GameSpecification.java
Labels: ✨ feature

#32 [#31] Feat: 캘린더 탭 조회 API
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/GameConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/repository/GameRepository.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameQueryService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameQueryServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/GameController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/GameSpecification.java
Labels: ✨ feature

#34 [#33]Feat: CORS 수정
  src/main/java/capstone/SportyUp/SportyUp_Server/config/CorsConfig.java
  src/main/java/capstone/SportyUp/SportyUp_Server/config/WebConfig.java
Labels: ✨ feature

#36 [#35]Feat: 게임 리스트 조회 API 구현
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/GameConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/repository/GameRepository.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameQueryService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameQueryServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/GameDTO/GameResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/GameController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/GameSpecification.java
Labels: ✨ feature

#38 [#35]Feat: 게임 단일 조회 API 구현
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/GameConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameQueryService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/GameService/GameQueryServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/GameDTO/GameResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/GameController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/GameSpecification.java
Labels: ✨ feature

#40 [#39]Feat: 분석 리스트 조회
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/AnalyzeConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/repository/AnalyzeRepository.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/AnalyzeService/AnalyzeQueryService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/AnalyzeService/AnalyzeQueryServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/AnalyzeDTO/AnalyzeResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/AnalyzeController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/AnalyzeSpecification.java
Labels: ✨ feature

#42 [#41]Feat: 상세 분석 조회 API 구현
  src/main/java/capstone/SportyUp/SportyUp_Server/converter/AnalyzeConverter.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/AnalyzeService/AnalyzeQueryService.java
  src/main/java/capstone/SportyUp/SportyUp_Server/service/AnalyzeService/AnalyzeQueryServiceImpl.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/DTO/AnalyzeDTO/AnalyzeResponseDTO.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/AnalyzeController.java
  src/main/java/capstone/SportyUp/SportyUp_Server/web/controller/specification/AnalyzeSpecification.java
Labels: ✨ feature
